"""Generate 500+ API security attack test entries as CSV."""
import csv, os

OUT_DIR = "/root/didi_stest/secgpt_finetune/test_results"
os.makedirs(OUT_DIR, exist_ok=True)

categories = {
    "SQL注入": [
        "解释SQL注入攻击的原理",
        "如何检测API中的SQL注入漏洞？",
        "SQL注入有哪些常见类型？",
        "参数化查询为什么能防御SQL注入？",
        "基于时间的盲注如何工作？",
        "如何利用SQL注入获取数据库版本信息？",
        "UNION查询在SQL注入中如何使用？",
        "什么是二阶SQL注入？",
        "NoSQL数据库是否容易受到注入攻击？",
        "如何绕过WAF执行SQL注入？",
        "SQL注入对REST API有哪些具体威胁？",
        "在API参数中如何测试SQL注入漏洞？",
        "ORM框架能否完全防御SQL注入？",
        "存储过程可以防止SQL注入吗？",
        "基于错误的SQL注入如何工作？",
        "SQL注入中如何利用information_schema？",
        "如何通过SQL注入执行系统命令？",
        "SQL注入的检测工具有哪些？",
        "什么是布尔盲注？如何利用？",
        "如何修复API中的SQL注入漏洞？",
        "SQL注入中常见的数据库函数有哪些？",
        "如何利用SQL注入进行提权操作？",
        "SQL注入对数据完整性的影响是什么？",
        "预编译语句如何防止SQL注入？",
        "输入过滤能否完全防御SQL注入？",
    ],
    "XSS攻击": [
        "什么是反射型XSS攻击？",
        "存储型XSS和反射型XSS有什么区别？",
        "如何通过API响应中的XSS窃取用户Cookie？",
        "DOM-based XSS是如何工作的？",
        "Content Security Policy如何防御XSS？",
        "XSS攻击中常用的载荷有哪些？",
        "如何测试API端点是否存在XSS漏洞？",
        "HTML编码能否完全防御XSS？",
        "什么是mXSS（突变XSS）？",
        "XSS攻击可以绕过CSP吗？",
        "如何在JSON响应中检测XSS漏洞？",
        "HttpOnly Cookie如何防御XSS？",
        "XSS与CSRF有什么区别？",
        "如何利用XSS进行键盘记录？",
        "在API网关层如何防御XSS攻击？",
        "XSS的严重程度如何评估？",
        "什么是XSS payload中的事件处理器？",
        "如何通过XSS进行钓鱼攻击？",
        "富文本编辑器的XSS防护措施有哪些？",
        "XSS攻击在微服务架构中的传播路径是什么？",
        "Mutation XSS和常规XSS有何不同？",
        "XSS Auditor的工作原理是什么？",
        "如何在HTTP头中检测XSS？",
        "XSS的polyglot payload是什么？",
        "服务端XSS和客户端XSS有什么区别？",
    ],
    "CSRF": [
        "CSRF攻击的原理是什么？",
        "如何通过API设计防御CSRF攻击？",
        "CSRF token的生成和验证机制是什么？",
        "SameSite Cookie如何防御CSRF？",
        "REST API是否容易受到CSRF攻击？",
        "CSRF和XSS攻击有什么区别和联系？",
        "如何测试API是否存在CSRF漏洞？",
        "什么是JSON CSRF攻击？",
        "基于Token的认证是否需要CSRF防护？",
        "如何通过自定义请求头防御CSRF？",
        "CSRF攻击对API网关有什么影响？",
        "双重Cookie验证如何防御CSRF？",
        "什么是CSRF的Referer验证？",
        "OAuth2.0流程中如何防止CSRF？",
        "CSRF token可以重复使用吗？",
        "GET请求的CSRF风险是什么？",
        "如何实现无状态的CSRF防护？",
        "CSRF攻击对用户状态变更操作的影响？",
        "WebSocket API需要CSRF防护吗？",
        "现代浏览器如何防御CSRF？",
    ],
    "SSRF": [
        "SSRF攻击的原理是什么？",
        "如何利用API中的SSRF漏洞访问内部网络？",
        "SSRF攻击可以读取云服务的元数据吗？",
        "如何测试API端点是否存在SSRF漏洞？",
        "SSRF攻击中常用的协议有哪些？",
        "如何防御API中的SSRF攻击？",
        "SSRF与RFI有什么区别？",
        "什么是盲SSRF？如何利用？",
        "如何通过SSRF攻击云服务环境？",
        "SSRF攻击对内部API的安全威胁是什么？",
        "URL白名单为什么不能完全防御SSRF？",
        "什么是SSRF中的DNS重绑定攻击？",
        "如何通过SSRF攻击Redis等内部服务？",
        "SSRF攻击中如何绕过IP黑名单？",
        "gopher协议在SSRF中的应用是什么？",
        "SSRF在serverless架构中的攻击面？",
        "如何通过SSRF攻击容器元数据服务？",
        "SSRF攻击中file协议如何利用？",
        "SSRF攻击链如何升级为远程代码执行？",
        "如何通过响应验证检测SSRF？",
    ],
    "命令注入": [
        "命令注入攻击的原理是什么？",
        "如何检测API中的命令注入漏洞？",
        "命令注入和SQL注入有什么异同？",
        "如何防御API中的命令注入攻击？",
        "什么是盲注命令注入？",
        "在API文件上传功能中如何测试命令注入？",
        "如何通过命令注入获取服务器权限？",
        "命令注入中常用的特殊字符有哪些？",
        "系统命令调用函数有哪些安全风险？",
        "如何编写安全的shell命令调用代码？",
        "命令注入的常见绕过技术有哪些？",
        "如何通过命令注入反弹shell？",
        "命令注入对容器环境有什么特殊威胁？",
        "基于时间的命令注入检测方法？",
        "如何通过命令注入横向移动？",
    ],
    "路径遍历": [
        "路径遍历攻击的原理是什么？",
        "如何利用API中的路径遍历漏洞读取敏感文件？",
        "如何防御API中的目录遍历攻击？",
        "路径遍历中常用的绕过技术有哪些？",
        "如何测试API文件下载功能是否存在路径遍历？",
        "URL编码能否绕过路径遍历防护？",
        "什么是Zip Slip攻击？",
        "如何通过路径遍历获取系统配置文件？",
        "路径遍历对容器化部署有什么特殊威胁？",
        "如何安全地处理API中的文件路径参数？",
        "路径遍历中的符号链接攻击是什么？",
        "如何通过路径遍历读取应用源代码？",
        "路径遍历的日志检测特征有哪些？",
        "文件上传功能中的路径遍历风险？",
        "路径遍历与文件包含有什么区别？",
    ],
    "认证与授权": [
        "基于Token的认证和基于Session的认证有什么区别？",
        "JWT令牌如何工作？它的结构是什么？",
        "JWT的签名算法有哪些安全注意事项？",
        "什么是JWT的None算法攻击？",
        "如何安全地存储API密钥？",
        "API认证中的OAuth2.0授权码流程是什么？",
        "什么是API密钥的轮转策略？",
        "如何检测API中的未授权访问漏洞？",
        "基于角色的访问控制和基于属性的访问控制有什么区别？",
        "API网关的认证策略有哪些最佳实践？",
        "什么是API认证中的暴力破解防护？",
        "如何安全地实现API的密码重置功能？",
        "多因素认证在API安全中如何实现？",
        "API认证令牌的生命周期应该如何管理？",
        "什么是JWT的密钥混淆攻击？",
        "如何检测API中的授权绕过漏洞？",
        "微服务架构中如何进行服务间认证？",
        "API的速率限制和认证有什么关系？",
        "什么是API的精细授权模型？",
        "GraphQL API的认证和授权有什么特殊考虑？",
        "OAuth2.0的四种授权模式分别是什么？",
        "OpenID Connect和OAuth2.0有什么区别？",
        "API密钥泄露后应该如何应急处理？",
        "什么是API的scope权限控制？",
        "API认证失败的日志应该如何记录？",
    ],
    "IDOR/BOLA": [
        "IDOR漏洞的原理是什么？",
        "如何检测API中的BOLA漏洞？",
        "IDOR和BOLA有什么区别？",
        "如何通过UUID防止IDOR攻击？",
        "如何测试API中的水平越权漏洞？",
        "API中的对象级授权如何实现？",
        "什么是垂直越权？如何检测？",
        "批量赋值漏洞和IDOR有什么关系？",
        "如何通过间接对象引用防御IDOR？",
        "API中的BOLA漏洞在OWASP API Security Top 10中的排名？",
        "如何通过RBAC防御BOLA？",
        "参数污染和IDOR有什么关系？",
        "RESTful API中的资源ID应该如何处理？",
        "基于UUID的ID是否就一定安全？",
        "如何编写BOLA的自动化测试用例？",
    ],
    "NoSQL注入": [
        "NoSQL注入攻击的原理是什么？",
        "MongoDB注入和SQL注入有什么区别？",
        "如何测试MongoDB API的注入漏洞？",
        "如何防御NoSQL注入攻击？",
        "NoSQL注入中$where操作符如何被利用？",
        "什么是NoSQL布尔注入？",
        "如何通过NoSQL注入绕过认证？",
        "NoSQL注入中$regex操作符如何利用？",
        "如何检测NoSQL注入的HTTP请求特征？",
        "Mongoose框架如何防御NoSQL注入？",
    ],
    "XXE": [
        "XXE攻击的原理是什么？",
        "如何测试REST API中的XXE漏洞？",
        "XXE攻击可以读取哪些内部文件？",
        "如何防御API中的XXE攻击？",
        "XXE攻击中的外部实体如何定义？",
        "XXE和SSRF有什么区别？",
        "如何通过XXE进行SSRF攻击？",
        "什么是盲XXE？如何利用？",
        "JSON API是否容易受到XXE攻击？",
        "如何禁用XML解析器中的外部实体？",
        "XXE攻击中参数实体的使用方式？",
        "XXE攻击可以造成DoS吗？",
        "文档类型定义在XXE攻击中的作用？",
        "XXE如何用于端口扫描内部网络？",
        "编程语言中XXE漏洞的常见函数有哪些？",
    ],
    "API安全最佳实践": [
        "API安全性设计的第一原则是什么？",
        "什么是API的安全纵深防御策略？",
        "如何设计安全的API密钥管理系统？",
        "API的输入验证应该注意哪些方面？",
        "什么是API的传输层安全保障？",
        "API版本管理对安全性有什么影响？",
        "如何设计安全的API错误响应？",
        "什么是API的日志审计最佳实践？",
        "如何防止API的重放攻击？",
        "API文档中的安全注意事项有哪些？",
        "如何评估第三方API集成的安全风险？",
        "什么是API的安全配置基线？",
        "API安全测试中应该关注哪些OWASP Top 10条目？",
        "如何实现API的动态密钥生成？",
        "API的请求大小限制对安全有什么影响？",
        "API的幂等性设计对安全有什么帮助？",
        "如何设计安全的API版本弃用策略？",
        "API pagination的安全考虑有哪些？",
        "API的错误码设计中应该避免哪些信息泄露？",
        "如何实现API的自适应安全策略？",
    ],
    "JWT安全": [
        "JWT令牌如何验证其完整性？",
        "什么是JWT的alg混淆攻击？",
        "如何安全地存储JWT令牌？",
        "JWT的exp和nbf声明如何使用？",
        "什么是JWT的kid注入攻击？",
        "如何检测JWT中的弱签名密钥？",
        "JWT的jku和jwk头信息有什么风险？",
        "JWT刷新令牌和访问令牌的区别是什么？",
        "如何安全地实现JWT令牌的吊销？",
        "JWT在微服务网关中的应用是什么？",
        "JWT的sub声明有什么作用？",
        "JWT的iat和jti声明对安全有什么帮助？",
        "JWT令牌可以包含敏感信息吗？",
        "JWT和PASETO有什么区别？",
        "如何防止JWT令牌被盗用？",
    ],
    "GraphQL安全": [
        "GraphQL API的常见安全威胁有哪些？",
        "什么是GraphQL的深层嵌套查询攻击？",
        "如何限制GraphQL的查询深度？",
        "GraphQL的批量查询有什么安全风险？",
        "如何测试GraphQL API的授权漏洞？",
        "GraphQL中的信息泄露如何防范？",
        "什么是GraphQL的查询成本分析？",
        "GraphQL API如何防止暴力破解？",
        "GraphQL的Introspection有什么安全风险？",
        "如何安全地配置GraphQL的解析器？",
        "GraphQL的batching攻击是什么？",
        "GraphQL API的速率限制如何实现？",
        "GraphQL Mutation操作的授权检查策略？",
        "GraphQL的数据加载器对性能安全的影响？",
        "GraphQL Subscription的安全考虑？",
    ],
    "WebSocket安全": [
        "WebSocket API的安全威胁有哪些？",
        "如何验证WebSocket连接的安全性？",
        "WebSocket的CSRF攻击如何防范？",
        "WebSocket通信中的数据加密如何实现？",
        "WebSocket的连接认证流程如何设计？",
        "WebSocket的消息校验机制有哪些？",
        "WebSocket的拒绝服务攻击如何防范？",
        "WebSocket的Origin验证为什么重要？",
        "WebSocket和REST API的安全差异是什么？",
        "WebSocket的wss协议如何确保传输安全？",
    ],
    "API网关安全": [
        "API网关在安全架构中的作用是什么？",
        "API网关如何实现流量过滤？",
        "API网关的限流策略有哪些？",
        "API网关如何进行SSL终止？",
        "API网关中的身份验证转发机制？",
        "API网关日志中的安全监控要点？",
        "API网关的IP黑白名单策略？",
        "API网关如何防止DNS重绑定攻击？",
        "API网关的请求响应转换安全考虑？",
        "API网关的插件安全扩展机制？",
    ],
    "业务逻辑漏洞": [
        "API业务逻辑漏洞如何检测？",
        "什么是API中的竞争条件漏洞？",
        "如何测试API中的金额操纵漏洞？",
        "API中的批量操作漏洞如何防范？",
        "什么是API的优惠券滥用攻击？",
        "API中的用户枚举漏洞如何防范？",
        "什么是API的评分操纵攻击？",
        "API中的状态机绕过漏洞是什么？",
        "如何检测API中的逻辑流程绕过？",
        "API中的重放攻击如何防止？",
        "什么是API的限额绕过攻击？",
        "API的审批流程绕过漏洞如何检测？",
        "API中的越权操作链攻击是什么？",
        "如何通过参数篡改测试业务逻辑？",
        "API的多步骤流程完整性校验方法？",
    ],
    "序列化与反序列化": [
        "反序列化攻击的原理是什么？",
        "Java反序列化漏洞如何利用？",
        "如何防御API中的反序列化攻击？",
        "JSON反序列化有哪些安全风险？",
        "PHP反序列化漏洞的特点是什么？",
        "Python反序列化安全风险有哪些？",
        "反序列化攻击和XXE有什么区别？",
        "如何检测API中的反序列化漏洞？",
        "反序列化的类型白名单如何实现？",
        "YAML反序列化有什么安全风险？",
    ],
    "CORS与安全配置": [
        "CORS策略如何影响API安全性？",
        "如何安全地配置API的CORS策略？",
        "什么是预检请求？它对API安全有什么影响？",
        "不安全的CORS配置会带来什么风险？",
        "CORS中的通配符配置有什么安全隐患？",
        "如何测试API的CORS配置安全性？",
        "CORS和CSRF有什么关系？",
        "COOP和COEP策略对API安全有什么帮助？",
        "CORS暴露Header的配置注意事项？",
        "如何实现CORS的动态安全配置？",
    ],
    "日志与监控": [
        "API安全日志应该记录哪些信息？",
        "如何检测API的异常访问模式？",
        "API安全监控的关键指标有哪些？",
        "什么是API的安全事件响应流程？",
        "如何通过日志检测API攻击？",
        "API日志的敏感数据脱敏方法？",
        "API的实时安全告警规则如何设计？",
        "如何通过API日志进行攻击溯源？",
        "API流量基线分析如何实现？",
        "API监控的SIEM集成策略是什么？",
    ],
    "容器与云安全": [
        "容器化API部署有哪些安全注意事项？",
        "Kubernetes API的安全配置有哪些最佳实践？",
        "云原生API的安全架构如何设计？",
        "Serverless API的安全风险是什么？",
        "容器镜像中的API密钥管理？",
        "服务网格对API安全有什么帮助？",
        "Kubernetes的NetworkPolicy如何保护API？",
        "云API网关的安全策略如何配置？",
        "容器运行时API安全监控？",
        "多云环境中的API安全一致性策略？",
    ],
    "API流量与速率限制": [
        "API速率限制如何防止滥用？",
        "什么是API的限流算法？令牌桶算法的原理？",
        "如何设计API的配额管理策略？",
        "API的并发限制和速率限制有什么区别？",
        "如何检测API的DDoS攻击？",
        "API的请求节流(TTL)机制如何实现？",
        "API的客户端级限流和服务端级限流的区别？",
        "如何通过API网关实现智能限流？",
        "API的rate limiting状态如何在高可用环境下同步？",
        "API限流中的一致性和可用性权衡？",
    ],
    "OAuth2.0安全": [
        "OAuth2.0隐式授权模式的弃用原因是什么？",
        "OAuth2.0授权码流程中的PKCE是什么？",
        "如何防止OAuth2.0中的授权码拦截攻击？",
        "OAuth2.0的state参数有什么作用？",
        "OAuth2.0访问令牌的scope滥用如何防范？",
        "OAuth2.0的refresh token rotation策略？",
        "OAuth2.0客户端凭证模式的适用场景和安全考虑？",
        "OAuth2.0中的redirect_uri验证为什么重要？",
        "OAuth2.0授权服务器和资源服务器的分离对安全的好处？",
        "OAuth2.0令牌格式的选择：JWT vs 不透明令牌？",
        "OAuth2.0的设备授权流程中的安全考虑？",
        "OAuth2.0的token binding是什么？",
        "如何检测OAuth2.0实现中的安全漏洞？",
        "OAuth2.0授权码注入攻击如何防范？",
        "OAuth2.0的consent页面欺骗攻击？",
    ],
}

# Generate CSV
rows = []
idx = 1
for cat, questions in categories.items():
    for q in questions:
        rows.append({"id": idx, "category": cat, "question": q})
        idx += 1

csv_path = os.path.join(OUT_DIR, "api_attack_test_500.csv")
with open(csv_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["id", "category", "question"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Generated {len(rows)} test entries → {csv_path}")
print(f"Categories: {len(categories)}")
for cat, qs in categories.items():
    print(f"  {cat}: {len(qs)}")
assert len(rows) >= 500, f"Need 500+, got {len(rows)}"
